### ISSUE TITLE
Define as constants

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/Hangman#1]
https://github.com/CapioIM/Hangman/blob/bce51f1377ab62b20fbe6df45b44e11fa50a76f3/Hangman/Program.cs#L13-L14

Better define those as constants. Those values should be fixed and never changed.

https://github.com/CapioIM/Hangman/blob/bce51f1377ab62b20fbe6df45b44e11fa50a76f3/Hangman/Program.cs#L32
https://github.com/CapioIM/Hangman/blob/bce51f1377ab62b20fbe6df45b44e11fa50a76f3/Hangman/Program.cs#L53

Use a variable to do your counting.
I don't know why you decided to use an static value. But static values are only once loaded and initalized class load. So in your case, the TRIES is initialized first with 10, you can also decrease it. But did you debug what happens when you replay the game and user chooses another round?

Better go for the constant and define a variable to do your counting.

**Comment by CapioIM** [comment]
its because I thought constant is static

**Comment by mayisa87** [comment]
It's not exactly the same. And for values that should never change at all, like a fixed information, I would rather use a constant. So values that never evwr should change, better use constants. 
Implicit they are static too, that's right.

I just would not recomment manipulating your static values. As you said they are kinda constants and the goal of a constant is, that the value stays the same.

**Comment by mayisa87** [comment]
Just wanted to add something. Later on you will for sure have some static fields that are used in logic and are of course changed too. 
It is just important to make a clear difference between constants, that give you a fixed value, abd are never changed. And on the other habd staic variables, that are once initialized when  starting you program and can then be used later on in code and also changed.

Like in case of you TRIES manipulating it and decreasing the value, made you ending up to have TRIES==0, and you never reset it to 10.
If you would have wanted to reset it, you would need TRIES=10; And to avoid 10 to be a magic number... again need a constant 😅 

That's why i suggested using a constant directly and a counter variable.
