### ISSUE TITLE
Avoid new String()

### ISSUE THREAD

**Issue by mayisa87** [CapioIM/Hangman#2]
https://github.com/CapioIM/Hangman/blob/bce51f1377ab62b20fbe6df45b44e11fa50a76f3/Hangman/Program.cs#L25

The goal of the exercise is to use the knowledge you already have. So you could have used  new char[LISTOFWORDS.Count] to create an array with the right amount of elements.
And then as you already did it seems, add the placeholders to array by using a loop.

https://github.com/CapioIM/Hangman/blob/bce51f1377ab62b20fbe6df45b44e11fa50a76f3/Hangman/Program.cs#L45

Same here, you could use "contains" to check if there is still a placeholder in your array, if not, you know the word was guessed.

Why not to use new String()? It creates an object each time, which means using storage which is only needed at this specific point.

**Comment by CapioIM** [comment]
new char[LISTOFWORDS.Count] this code creates array with amount of elements equal to amount of entries in list.
