### ISSUE TITLE
Is this constant really necessary?

### ISSUE THREAD

**Issue by incredibleLeitman** [CapioIM/Hangman#3]
https://github.com/CapioIM/Hangman/blob/001d33ceaeca60a6e7c4d1a8630f470b9a716328/Hangman/Program.cs#L13
Usually constants for value 0 are not a thing because this is kinda a special value and understandable from the context.

In this use case, you also only use this constant for generating a random number, 
whereas Random.Next has an overload (different version of that function that accepts other parameters) that only takes the upper bound and generates a random number between 0 and the given value:
https://learn.microsoft.com/en-us/dotnet/api/system.random.next?view=net-7.0#system-random-next(system-int32)

**Comment by CapioIM** [comment]
no ,if minValue is 0 it is not necessary to put in Random.Next
